### PR TITLE
Add TALL stack preset

### PR DESCRIPTION
**Pull request by innocenzi**
There's the official front-end preset already, but I've recently made a tool dedicated to presets. This is the TALL preset for this tool, which can be installed with just one command. 

Note that the content of the preset is mostly the same as the front-end one.

```bash
npx use-preset laravel-tall
```

### CODE REVIEW

**Comment by driesvints** [comment]
Is there a way we can differentiate the title with the one above it?

**Comment by innocenzi** [comment]
Ah, I thought it would be problematic, too. The tool is called Preset so it doesn't help. Maybe call mine `Laravel TALL Preset`, and the official one `Laravel TALL Front-end Preset` or something along those lines?

**Comment by driesvints** [comment]
Is the difference that yours is a JS library? If so we could add (PHP) and (JS) respectively.

**Comment by innocenzi** [comment]
Hmm, that would be confusing, people could think it's installing something JavaScript-related. 

I think the best way would be to mention `front-end` in the official one's name, since it's the name of the organisation it's hosted on? Or just not change the name, since they're both actually the same preset, but use different tools—their description differentiate them. 

We actually have a few duplicate names on [`awesome-tailwindcss`](https://github.com/aniftyco/awesome-tailwindcss), I don't think that's a big deal. 

If you really want a name change, I'll think about something later tonight and update the PR

**Comment by driesvints** [comment]
Yeah you're right. It's probably not that big of a deal. Thanks for the PR!

**Pull request merged**
